name: Pull Request Card Automation

on: 
  pull_request:
    types: [opened]
    branches:
      - '*'
jobs:
  PR-Card-Automation:
    runs-on: ubuntu-latest
    steps: 
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with: 
          project: resumaker
          column: Code Review
          repo-token: ${{secrets.PAO}}